[package]
name = "rust_random_card"
version = "0.1.0"
authors = ["robbert on nuc <robbert@groen-engineering.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
